In [2]:
print(2)

2


In [1]:
import numpy as np

vector

In [5]:
np.array((1 , 2, 2))

array([1, 2, 2])

sub_vector  , Block or stacked vectors

In [2]:
a = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
result = [x[1:4] for x in a[0:1]]
print(result)


[[2, 3, 4]]


Indexing

In [6]:
a[1][1:3] , a[0][2]

([7, 8], 3)

Zero vectors

In [21]:
np.zeros(((2 , 3 , 1 )))

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

Ones Vector

In [25]:
np.ones((2 , 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

(standard) unit vector

In [24]:
def unit_vector(i , n):
       #create a vector of zeros of size n
       e = np.zeros(n)
       #set ith element to 1
       e[i-1] = 1
       return e

e_unit = unit_vector(2 , 3)
print(e_unit)

[0. 1. 0.]


Sparsity : nnz(x)  The number of the nonzero entries

In [6]:
np.count_nonzero([1,0,2,0,0,0,0,3,0,0,0,0,0,0])

3

In [12]:
test_list = [1,0,0,0,3,0,0,1,0,0,2]
sparsity_pattern = np.nonzero(test_list)
print(test_list)
print(sparsity_pattern[0])

[1, 0, 0, 0, 3, 0, 0, 1, 0, 0, 2]
[ 0  4  7 10]


Image in array format (Gray-Scale Array to Image Conversion)

In [4]:
from PIL import Image
# import numpy as np

In [9]:
# open the Image
img_file = Image.open("p.jpg")

#convert img to gray-scale(8-bit)
img_gray = img_file.convert("L") #or "1"

#Display the gray scale img
img_gray.show()

#convert gray img to a Numpy array:
grayScale_array = np.array(img_gray)
# Now `grayscale_array` contains the pixel values as a 2D array
grayScale_array

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [10]:
#convert th Numpy array back to an img object
restored_img = Image.fromarray(grayScale_array)
restored_img.show()